<!DOCTYPE html>
<html lang="en"><head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"><!-- Begin Jekyll SEO tag v2.8.0 -->
<title>Understanding PHP Exception Handling | ulyssesonline</title>
<meta name="generator" content="Jekyll v4.3.2" />
<meta property="og:title" content="Understanding PHP Exception Handling" />
<meta name="author" content="ulysses" />
<meta property="og:locale" content="en_US" />
<meta name="description" content="PHP 5 has an exception handling model similar to that of other programming languages. Exception handling is used primarily to modify the control of a program by using the “try” and “catch” method. Throwing and catching exceptions allow programmers to handle errors gracefully. Let’s say you have a function called inverse() which simply returns an inverse of the supplied integer. Here are the details of the function." />
<meta property="og:description" content="PHP 5 has an exception handling model similar to that of other programming languages. Exception handling is used primarily to modify the control of a program by using the “try” and “catch” method. Throwing and catching exceptions allow programmers to handle errors gracefully. Let’s say you have a function called inverse() which simply returns an inverse of the supplied integer. Here are the details of the function." />
<link rel="canonical" href="http://0.0.0.0:4000/ulyssesonline/2009/10/18/understanding-php-exception-handling/" />
<meta property="og:url" content="http://0.0.0.0:4000/ulyssesonline/2009/10/18/understanding-php-exception-handling/" />
<meta property="og:site_name" content="ulyssesonline" />
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2009-10-18T17:40:50+00:00" />
<meta name="twitter:card" content="summary" />
<meta property="twitter:title" content="Understanding PHP Exception Handling" />
<script type="application/ld+json">
{"@context":"https://schema.org","@type":"BlogPosting","author":{"@type":"Person","name":"ulysses"},"dateModified":"2009-10-18T17:40:50+00:00","datePublished":"2009-10-18T17:40:50+00:00","description":"PHP 5 has an exception handling model similar to that of other programming languages. Exception handling is used primarily to modify the control of a program by using the “try” and “catch” method. Throwing and catching exceptions allow programmers to handle errors gracefully. Let’s say you have a function called inverse() which simply returns an inverse of the supplied integer. Here are the details of the function.","headline":"Understanding PHP Exception Handling","mainEntityOfPage":{"@type":"WebPage","@id":"http://0.0.0.0:4000/ulyssesonline/2009/10/18/understanding-php-exception-handling/"},"url":"http://0.0.0.0:4000/ulyssesonline/2009/10/18/understanding-php-exception-handling/"}</script>
<!-- End Jekyll SEO tag -->
<link rel="stylesheet" href="/ulyssesonline/assets/main.css"><link type="application/atom+xml" rel="alternate" href="http://0.0.0.0:4000/ulyssesonline/feed.xml" title="ulyssesonline" /></head>
<body><header class="site-header" role="banner">

  <div class="wrapper"><a class="site-title" rel="author" href="/ulyssesonline/">ulyssesonline</a><nav class="site-nav">
        <input type="checkbox" id="nav-trigger" class="nav-trigger" />
        <label for="nav-trigger">
          <span class="menu-icon">
            <svg viewBox="0 0 18 15" width="18px" height="15px">
              <path d="M18,1.484c0,0.82-0.665,1.484-1.484,1.484H1.484C0.665,2.969,0,2.304,0,1.484l0,0C0,0.665,0.665,0,1.484,0 h15.032C17.335,0,18,0.665,18,1.484L18,1.484z M18,7.516C18,8.335,17.335,9,16.516,9H1.484C0.665,9,0,8.335,0,7.516l0,0 c0-0.82,0.665-1.484,1.484-1.484h15.032C17.335,6.031,18,6.696,18,7.516L18,7.516z M18,13.516C18,14.335,17.335,15,16.516,15H1.484 C0.665,15,0,14.335,0,13.516l0,0c0-0.82,0.665-1.483,1.484-1.483h15.032C17.335,12.031,18,12.695,18,13.516L18,13.516z"/>
            </svg>
          </span>
        </label>

        <div class="trigger"><a class="page-link" href="/ulyssesonline/about.html">About</a></div>
      </nav></div>
</header>
<main class="page-content" aria-label="Content">
      <div class="wrapper">
        <article class="post h-entry" itemscope itemtype="http://schema.org/BlogPosting">

  <header class="post-header">
    <h1 class="post-title p-name" itemprop="name headline">Understanding PHP Exception Handling</h1>
    <p class="post-meta">
      <time class="dt-published" datetime="2009-10-18T17:40:50+00:00" itemprop="datePublished">Oct 18, 2009
      </time>• <span itemprop="author" itemscope itemtype="http://schema.org/Person"><span class="p-author h-card" itemprop="name">ulysses</span></span></p>
  </header>

  <div class="post-content e-content" itemprop="articleBody">
    <p>PHP 5 has an exception handling model similar to that of other programming languages. Exception handling is used primarily to modify the control of a program by using the “<strong>try</strong>” and “<strong>catch</strong>” method. Throwing and catching exceptions allow programmers to handle errors gracefully. Let’s say you have a function called inverse() which simply returns an inverse of the supplied integer. Here are the details of the function.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>&lt;pre lang="php"&gt;
function inverse($x) {
   return 1/$x;
}
</code></pre></div></div>

<p>Simple. The problem with this function is when we pass an integer with a value of zero. As you recall in math class, you can’t divide a number by zero. So, we will modify the function by adding an exception handler to it. I will introduce a command called “<strong>throw</strong>” accompanied by an error message.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>&lt;pre lang="php"&gt;
function inverse($x) {
  if ($x==0) { 
    throw new Exception('Division by zero.');
    echo "I'm zero. Don't let me be the denominator."; 
  } else { 
    return 1/$x;
  }
}
</code></pre></div></div>

<p>The modified function now has an “<strong>if statement</strong>” to check if the integer being passed is zero. If it is, we will invoke the “<strong>throw new Exception</strong>” command with an error message inside a parenthesis and encapsulated by single quotes. In addition, I’ve added an echo message immediately after the throw command that I will explain later. Now, let’s use our modified inverse() function with the “<strong>try</strong>” and “<strong>catch</strong>” commands.</p>

<div class="language-plaintext highlighter-rouge"><div class="highlight"><pre class="highlight"><code>&lt;pre lang="php"&gt;
try {
  inverse();
} 
catch (Exception $e) {
    echo $e-&gt;getMessage();
}
</code></pre></div></div>

<p>The inverse() function is inside try { } block followed by a catch { } block that simply prints the error message. This is the syntax when using try and catch commands. Every try block must be followed by a catch block. Now back to our function example. Remember the echo “<strong>I’m zero. Don’t let me be the denominator</strong>” statement? That echo statement never gets executed because when an exception is detected by the try command, it will immediately send the program to the catch block to print the error message.</p>

<p>This is how PHP’s Exception Handling works. If you have comments or questions about PHP Exception Handling, leave me a comment.</p>

  </div><a class="u-url" href="/ulyssesonline/2009/10/18/understanding-php-exception-handling/" hidden></a>
</article>

      </div>
    </main><footer class="site-footer h-card">
  <data class="u-url" href="/ulyssesonline/"></data>

  <div class="wrapper">

    <div class="footer-col-wrapper">
      <div class="footer-col">
        <p class="feed-subscribe">
          <a href="http://0.0.0.0:4000/ulyssesonline/feed.xml">
            <svg class="svg-icon orange">
              <use xlink:href="/ulyssesonline/assets/minima-social-icons.svg#rss"></use>
            </svg><span>Subscribe</span>
          </a>
        </p>
      </div>
      <div class="footer-col-right">
        <p>Copyright &copy; 2023</p>
      </div>
    </div>

    <div class="social-links"><ul class="social-media-list"></ul>
</div>

  </div>

</footer>

</body>

</html>
